ARG OS_VERSION=44
FROM fedora:${OS_VERSION}

RUN dnf update -y
RUN dnf install -y \
      which curl wget python3 patch \
      cmake pkg-config gcc-c++ libtool \
      openssl-devel openssl-devel-engine cyrus-sasl-lib cyrus-sasl-devel libssh-devel \
      brotli-devel libidn2-devel libnghttp2-devel curl-devel libpsl-devel libunistring-devel \
      krb5-devel openldap-devel lz4-devel snappy-devel libzstd-devel

WORKDIR /usr/src/kcat

# Copy the compatibility patch for bootstrap.sh
COPY bootstrap-compat.patch /tmp/

# argument BUILD_TIMESTAMP is used to disable caching of build step
ARG BUILD_TIMESTAMP=0

ARG LIBRDKAFKA_VERSION=v2.14.1
# Apply bootstrap fixes for current Fedora toolchains
RUN patch -p0 < /tmp/bootstrap-compat.patch && \
  export CMAKE_POLICY_VERSION_MINIMUM=3.5 && \
  LIBRDKAFKA_VERSION=${LIBRDKAFKA_VERSION} ./bootstrap.sh; result=$?; \
  chmod -R o=rwX ./tmp-bootstrap; \
  bash -c "if [ $result -ne 0 ]; then false; fi"
RUN bash -c "if [ -f kafkacat ]; then cp kafkacat kcat; fi"
