name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        version:
          - latest:1.8
          - 1.8.2-1.7.1
          - 1.7.0-1.7.1
          - 1.6.2-1.7.1
          - 1.8.2-1.6.0
          - 1.7.0-1.6.0
          - 1.6.2-1.6.0
          - 1.8.2-1.5.0
          - 1.7.0-1.5.0
          - 1.6.2-1.5.0
    runs-on: ubuntu-22.04
    steps:
      - name: Install Podman
        run: |
          sudo apt-get install -y podman
          mkdir -p ~/.config/containers/
          echo 'unqualified-search-registries = ["docker.io"]' > ~/.config/containers/registries.conf
      - name: Install kcat runtime dependencies
        run: sudo apt-get install -y libsasl2-2 curl
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          version: ${{ matrix.version }}
          command: kcat -h
