name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        version:
          - 2.14.1-1.7.1
    runs-on: ubuntu-24.04
    steps:
      - name: Install Podman
        run: |
          sudo apt-get install -y podman
          mkdir -p ~/.config/containers/
          echo 'unqualified-search-registries = ["docker.io"]' > ~/.config/containers/registries.conf
      - name: Install kcat runtime dependencies
        run: sudo apt-get install -y libsasl2-2 curl
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          version: ${{ matrix.version }}
          command: kcat -h
