name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        version:
          - latest
          - 1.7.1-1.9.2
          - 1.7.1-1.8.2
          - 1.7.1-1.7.0
          - 1.7.1-1.6.2
          - 1.6.0-1.9.2
          - 1.6.0-1.6.2
          - 1.5.0-1.9.2
          - 1.5.0-1.6.0
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          version: ${{ matrix.version }}
          command: kcat -h
